---
title: "Central Code"
author: '620'
date: "2/28/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
t1 = read_excel(path = './rawdata/t1.xlsx',
                col_types = c("date","numeric","numeric","numeric","date",'text','logical'))
t2 = read_excel(path = './rawdata/t2.xlsx',
                  col_types = c("date","numeric","numeric","numeric","date",'text','logical'))
t3 = read_excel(path = './rawdata/t3.xlsx',
                col_types = c("date","numeric","numeric","numeric","date",'text','logical'))
for (i in 1:length(t3$date)) {
  t3$pickups_1st[i] = ymd_hms(paste(as.character(t3$date[i]), strsplit(as.character(t3$pickups_1st[i]),split = " ")[[1]][2]))
}

colnames(t2) = c('date',"total_st","social_st","pickups","pickups_1st","weekday","if_weekend")
colnames(t3) = c('date',"total_st","social_st","pickups","pickups_1st","weekday","if_weekend")
for (i in 1:length(t2$date)) {
  t2$pickups_1st[i] = ymd_hms(paste(as.character(t2$date[i]), strsplit(as.character(t2$pickups_1st[i]),split = " ")[[1]][2]))
}

t1[['first_pick_time']] = hour(t1$pickups_1st) + minute(t1$pickups_1st)/60
t2[['first_pick_time']] = hour(t2$pickups_1st) + minute(t2$pickups_1st)/60
t3[['first_pick_time']] = hour(t3$pickups_1st) + minute(t3$pickups_1st)/60
t1 = cbind(t1,id = 1)
t2 = cbind(t2,id = 2)
t3 = cbind(t3,id = 3)
tt = rbind(t1,t2,t3)

```

#federated learning
```{r}
n = n1+n2+n3
x_bar = (n1*x_bar_1 + n2*x_bar_2+n3*x_bar_3)/n
x_bar = (n1*y_bar_1 + n2*y_bar_2+n3*y_bar_3)/n
```

```{r}
ssx = ssx1+ssx2+ssx3
ssxy = ssxy1 +ssxy2+ ssxy3
  
beta1_hat = ssxy/ssx
beta0_hat = y_bar- beta1_hat*x_bar
```

```{r}
MSE_total = (SSE1+SSE2+SSE3)/(n-2)
var_beta1_hat = MSE_total/ssx
st_beta1_hat = sqrt(var_beta1_hat)
p_value_beta1 = pt(beta1_hat/st_beta1_hat,n-2,lower.tail = F)*2
var_beta0_hat = MSE_total*(1/n + x_bar^2/ssx)
st_beta0_hat = sqrt(var_beta0_hat)
p_value_beta0 = pt(beta0_hat/st_beta0_hat,n-2,lower.tail = F)*2
```

#meta learning 
```{r}

```

