---
title: "620pj"
author: "Han Zhang"
date: "2/24/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(tidyr)
library(readr)
library(readxl)
library(lubridate)
```

### 把clean data 导入分成三个table t1,t2,t3
### 把三个table 融合成一个table tt
```{r}
t1 = read_excel(path = './rawdata/t1.xlsx',
                col_types = c("date","numeric","numeric","numeric","date",'text','logical'))
t2 = read_excel(path = './rawdata/t2.xlsx',
                  col_types = c("date","numeric","numeric","numeric","date",'text','logical'))
t3 = read_excel(path = './rawdata/t3.xlsx',
                col_types = c("date","numeric","numeric","numeric","date",'text','logical'))
for (i in 1:length(t3$date)) {
  t3$pickups_1st[i] = ymd_hms(paste(as.character(t3$date[i]), strsplit(as.character(t3$pickups_1st[i]),split = " ")[[1]][2]))
}

colnames(t2) = c('date',"total_st","social_st","pickups","pickups_1st","weekday","if_weekend")
colnames(t3) = c('date',"total_st","social_st","pickups","pickups_1st","weekday","if_weekend")
for (i in 1:length(t2$date)) {
  t2$pickups_1st[i] = ymd_hms(paste(as.character(t2$date[i]), strsplit(as.character(t2$pickups_1st[i]),split = " ")[[1]][2]))
}

t1[['first_pick_time']] = hour(t1$pickups_1st) + minute(t1$pickups_1st)/60
t2[['first_pick_time']] = hour(t2$pickups_1st) + minute(t2$pickups_1st)/60
t3[['first_pick_time']] = hour(t3$pickups_1st) + minute(t3$pickups_1st)/60
t1 = cbind(t1,id = 1)
t2 = cbind(t2,id = 2)
t3 = cbind(t3,id = 3)
# calculate the screen time except for the social purpose 
t1[['other_st']] = t1[['total_st']] - t1[['social_st']]
t2[['other_st']] = t2[['total_st']] - t2[['social_st']]
t3[['other_st']] = t3[['total_st']] - t3[['social_st']]
tt = rbind(t1,t2,t3)
```


### federated learning
先算各自outcome的均值y1 y2 y3 汇总得到ybar
算 predictor的均值x1，x2,x3  算得xbar
n1,n2,n3 represent the number of observation
```{r}
n1 = nrow(t1)
n2 = nrow(t2)
n3 = nrow(t3)
n = n1+n2+n3
x = 'pickups'
y = 'social_st'
x_bar = (sum(t1[[x]]) +sum(t2[[x]]) +sum(t3[[x]]))/n
y_bar = (sum(t1[[y]])+sum(t2[[y]]) +sum(t3[[y]]))/n

```
返回均值 用于算ssx ssy ssxy
```{r}
ssx1 = sum((t1[[x]] - x_bar)^2)
ssx2 = sum((t2[[x]] - x_bar)^2)
ssx3 = sum((t3[[x]] - x_bar)^2)

ssx = ssx1+ssx2+ssx3

ssy1 = sum((t1[[y]] - y_bar)^2)
ssy2 = sum((t2[[y]] - y_bar)^2)
ssy3 = sum((t3[[y]] - y_bar)^2)
ssy = ssy1+ssy2+ssy3

ssxy1 = sum((t1[[x]] - x_bar)*(t1[[y]] - y_bar))
ssxy2 = sum((t2[[x]] - x_bar)*(t2[[y]] - y_bar))
ssxy3 = sum((t3[[x]] - x_bar)*(t3[[y]] - y_bar))

ssxy = ssxy1 +ssxy2+ ssxy3
  
beta1_hat = ssxy/ssx
beta0_hat = y_bar- beta1_hat*x_bar
```

把返回的beta1 beta0 用于算各自的fitted value 的MSE
和总体的mse

```{r}
MSE1 = sum((t1[[y]] - t1[[x]] * beta1_hat-beta0_hat)^2)
MSE2 = sum((t2[[y]] - t2[[x]] * beta1_hat-beta0_hat)^2)
MSE3 = sum((t3[[y]] - t3[[x]] * beta1_hat-beta0_hat)^2)
MSE_total = (MSE1+MSE2+MSE3)/(n-2)
```

将返回的mse_total用于计算var

```{r}
var_beta1_hat = MSE_total/ssx
st_beta1_hat = sqrt(var_beta1_hat)
p_value_beta1 = pt(beta1_hat/st_beta1_hat,n-2,lower.tail = F)*2
var_beta0_hat = MSE_total*(1/n + x_bar^2/ssx)
st_beta0_hat = sqrt(var_beta0_hat)
p_value_beta0 = pt(beta0_hat/st_beta0_hat,n-2,lower.tail = F)*2
cat('Beta1:',beta1_hat,'\n')
cat('st error',st_beta1_hat)
st_beta0_hat

```
```{r}
beta0_row = c(round(c(beta0_hat,st_beta0_hat,beta0_hat/st_beta0_hat),4),format(p_value_beta0,scientific = T,digits = 4))
beta1_row = round(c(beta1_hat,st_beta1_hat,beta1_hat/st_beta1_hat,p_value_beta1),4)
table2 = rbind(beta0_row,beta1_row)
row.names(table2) =c('(Intercept)',"Pickups")
knitr::kable(table2,caption = 'Table 2. The parameters of simple linear model', align ='cccc',col.names= c('Estimate','Std. Error','t value','P value'))%>% kable_styling(bootstrap_options = c("striped"),full_width = F)%>% save_kable('table2.png',zoom=2)
```


```{r}
library(knitr)
library(kableExtra)
idn = c(1,2,3)
obs = c(n1,n2,n3)
x_bar_indi = round(c(mean(t1$pickups),mean(t2$pickups),mean(t3$pickups)),2)
y_bar_indi = round(c(mean(t1$social_st),mean(t2$social_st),mean(t3$social_st)),2)
sumofsquarex = round(c(ssx1,ssx2,ssx3),2)
sumofsquarexy = round(c(ssxy1,ssxy2,ssxy3),2)
sse = round(c(MSE1,MSE2,MSE3),2)
table4 = cbind(idn,obs,x_bar_indi,y_bar_indi,sumofsquarex,sumofsquarexy,sse)
knitr::kable(table4,caption = 'Table 1. The sample summary statistics',align ='ccccccc',col.names= c('ID','Observations Number (n)','Average of Pickup\n Times (X)','Average of Social Screen Time (Y)','SSX','SSXY','SSE'))%>% kable_styling(bootstrap_options = c("striped"),full_width = F)%>% save_kable('table4.png',zoom=2)
```



```{r}
comfirm = lm(as.formula(paste(y,'~', x)),data=tt)
summary(comfirm)
```
### meta learning

$$\begin{equation} 
\bar{x} = \frac{\sum_{i=1}^{3}\bar{x}_i \times n_i}{n_1 +n_2+n_3}, \bar{y} = \frac{\sum_{i=1}^{3}\bar{y}_i \times n_i}{n_1 +n_2+n_3}\\
SSX_k = \sum_{i=1}^{n_k}(x_{ki} -\bar{x})^2, SSXY_k = \sum_{i=1}^{n_k}[(x_{ki} -\bar{x})\times (y_{ki} -\bar{y})] \\ \beta_1 = \frac{\sum_{k=1}^3 SSXY_k}{\sum_{k=1}^{3} SSX_k}, \beta_0 = \bar{y} - \bar{x}\times\beta_1 \\
SSE_k = \sum_{i=1}^{n_k} (y_{ki} - \beta_0 -\bar{x}_{ki}\times\beta_1 )^2, 
MSE=\hat{\sigma}^2 = \frac{\sum_{k=1}^{3}SSE_k}{n-2} \\
Var(\beta_1) = \frac{\hat{\sigma}^2}{SSX},Var(\beta_0)= \hat{\sigma}^2 \times (\frac{1}{n} + \frac{\bar{x}^2}{SSX})

\end{equation}
$$


$$\begin{aligned}
\bar{x} = \frac{\sum_{i=1}^{3}\bar{x}_i \times n_i}{n_1 +n_2+n_3},\bar{y} = \frac{\sum_{i=1}^{3}\bar{y}_i \times n_i}{n_1 +n_2+n_3}
\label{}
\end{aligned}
$$

$$\begin{aligned}
SSX_k = \sum_{i=1}^{n_k}(x_{ki} -\bar{x})^2, SSXY_k = \sum_{i=1}^{n_k}[(x_{ki} -\bar{x})\times (y_{ki} -\bar{y})]
\end{aligned}
$$

$$\begin{aligned}
\beta_1 = \frac{\sum_{k=1}^3 SSXY_k}{\sum_{k=1}^{3} SSX_k}, \beta_0 = \bar{y} - \bar{x}\times\beta_1
\end{aligned}
$$


$$\begin{aligned}
SSE_k = \sum_{i=1}^{n_k} (y_{ki} - \beta_0 -\bar{x}_{ki}\times\beta_1 )^2, 
MSE=\hat{\sigma}^2 = \frac{\sum_{k=1}^{3}SSE_k}{n-2}
\end{aligned}
$$


$$\begin{aligned}
Var(\beta_1) = \frac{MSE}{SSX},Var(\beta_0)= MSE \times (\frac{1}{n} + \frac{\bar{x}^2}{SSX})
\end{aligned}
$$

### beta 
```{r}
mul_fit  = lm(social_st ~ pickups+if_weekend+first_pick_time,data = tt)
summary(mul_fit)
```

