---
title: "620project"
author: "Xin Luo"
date: "2022/2/26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Meta learning

```{r cars}
library(readxl)
library(lubridate)
t1 <- read_excel('t1.xlsx', col_types = c('date', 'numeric', 'numeric', 'numeric'
                                        ,'date', 'text', 'logical'))
t2 <- read_excel('t2.xlsx', col_types = c('date', 'numeric', 'numeric', 'numeric'
                                        ,'date', 'text', 'logical'))
t3 <- read_excel('t3.xlsx', col_types = c('date', 'numeric', 'numeric', 'numeric'
                                        ,'date', 'text', 'logical'))
```

```{r}
for (i in 1:length(t3$date)) {
  t3$pickups_1st[i] = ymd_hms(paste(as.character(t3$date[i]), strsplit(as.character(t3$pickups_1st[i]),split = " ")[[1]][2]))
}
colnames(t2) = c('date',"total_st","social_st","pickups","pickups_1st","weekday","if_weekend")
for (i in 1:length(t2$date)) {
  t2$pickups_1st[i] = ymd_hms(paste(as.character(t2$date[i]), strsplit(as.character(t2$pickups_1st[i]),split = " ")[[1]][2]))
}
t1[['first_pick_time']] = hour(t1$pickups_1st) + minute(t1$pickups_1st)/60
t2[['first_pick_time']] = hour(t2$pickups_1st) + minute(t2$pickups_1st)/60
t3[['first_pick_time']] = hour(t3$pickups_1st) + minute(t3$pickups_1st)/60

t1['if_weekend'] = 1 * t1$if_weekend
t2['if_weekend'] = 1 * t2$if_weekend
t3['if_weekend'] = 1 * t3$if_weekend
```

## Separated linear regression
```{r pressure, echo=FALSE}
lm1 = lm(t1$social_st ~ t1$pickups + t1$first_pick_time + t1$if_weekend)
s1 = summary(lm1)
lm2 = lm(t2$social_st ~ t2$pickups + t2$first_pick_time + t2$if_weekend)
s2 = summary(lm2)
lm3 = lm(t3$social_st ~ t3$pickups + t3$first_pick_time + t3$if_weekend)
s3 = summary(lm3)
```

## meta learning
```{r}
p = 3
for(i in c(1 : p)){  
  beta1 = s1$coefficients[i, 1]
  beta2 = s2$coefficients[i, 1]
  beta3 = s3$coefficients[i, 1]
  varbeta1 = s1$coefficients[i, 2]^2
  varbeta2 = s2$coefficients[i, 2]^2
  varbeta3 = s3$coefficients[i, 2]^2
  
  c1 = (1 / varbeta1) / (1 / varbeta1 + 1 / varbeta2 + 1 / varbeta3)
  c2 = (1 / varbeta2) / (1 / varbeta1 + 1 / varbeta2 + 1 / varbeta3)
  c3 = (1 / varbeta3) / (1 / varbeta1 + 1 / varbeta2 + 1 / varbeta3)
  beta_m = c1 * beta1 + c2 * beta2 + c3 * beta3
  
  print(paste('Meta beta', i - 1, ':', round(beta_m, 4)))
}
```

## combined linear regression
```{r}
colnames(t1) <- c("date", "total_st", "social_st", "pickups", "pickup_1st", "weekday", "if_weekend", "first_pick_time")
colnames(t2) <- c("date", "total_st", "social_st", "pickups", "pickup_1st", "weekday", "if_weekend","first_pick_time")
colnames(t3) <- c("date", "total_st", "social_st", "pickups", "pickup_1st", "weekday", "if_weekend","first_pick_time")
ad = rbind(t1, t2, t3)
alm = lm(ad$social_st ~ ad$pickups + ad$first_pick_time + ad$if_weekend)
summary(alm)
```